using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using TMPro;

public class QuestionArray_Level2 : MonoBehaviour
{
    public TextMeshProUGUI questionText;
    public TextMeshProUGUI answer1Text;
    public TextMeshProUGUI answer2Text;
    public TextMeshProUGUI answer3Text;
    public TextMeshProUGUI explanationText;

    string[] questions = new string[]
    {
        // N-1
        "The IP, OSPF and BGP protocols are a ____ layer protocol.",
        // N-2
        "The length of IPv____ address is 128 bits.",
        // N-3
        "The data unit used in Network layer is known as ____",
        // N-4
        "The process of dividing a packet into multiple fragments is known as ____",
        // N-5
        "The ____ field in IP header specifies the number of routers that a packet can pass through.",
        // N-6
        "The value of 1 in the Protocol field in the packet header identifies the ____ protocol.",
        // N-7
        "____ address identifies a host on a network and is used to fine the destination for data.",
        // N-8
        "The default subnet mask for class B in IP address is ____",
        // N-9
        "The default subnet mask for class C in IP address is ____",
        // N-10
        "____ address is a special IP address used to send data to all hosts on a network.",
        // N-11
        "____ address identifies a network segment.",
        // N-12
        "Choose the correct range of class A within the private IP address.",
        // N-13
        "The range of class ____ in the private IP address is 192.168.0.0 - 192.168.255.255.",
        // N-14
        "127.0.0.0/8 is a ____ address.",
        // N-15
        "____ is an auxiliary protocol of the IP protocol. It is used to transmit error and error control information between network devices.",
        // N-16
        "____ is a network device that forwards packet to a destination subnet based on routes.",
        // N-17
        "The ____ component in a IP routing table indicates the next-hop address used by the router to forward the data packet to the destination subnet.",
        // N-18
        "In a routing table, the ____ routes are manually configured by network administrators.",
        // N-19
        "____ routes in a routing table are automatically generated by the router.",
        // N-20
        "____ routes in a routing table are the routes learned by the routing protocols, such as OSPF,RIP and BGP.",
        // N-21
        "The preference value of the static route in a routing table is ____ by default.",
        // N-22
        "Choose the preference value of OSPF internal route in a routing table.",
        // N-23
        "____ routes are used only when the incoming packets do not match any routing entry in an IP routing table.",
        // N-24
        "The OSPF and RIP protocols are classified as the ____ routing protocols that runs within an Autonomous System (AS).",
        // N-25
        "The size of IP routing table is reduced by implementing ____",
        // N-26
        "OSPF is a ____ routing protocol.",
        // N-27
        "____ is the preference value of the direct route in a routing table.",
        // N-28
        "Area ____ in OSPF is a backbone area.",
        // N-29
        "The ____ packet in OSPF is periodically sent to discover and maintain the neighbour relationship between routers.",
        // N-30
        "Only the ____ and BDR can establish adjacencies with other OSPF routers.",
        // N-31
        "An OSPF domain is divided into multiple ____ to support larger-scale network.",
        // N-32
        "____ type of OSPF router exchanges routing information with other Autonomous Systems (AS).",
        // N-33
        "The Origin, AS_PATH and Next-Hop attributes are classified as the ____ attribute.",
        // N-34
        "AS is an abbreviation for ____. It is a set of routers that is managed by a single organization and uses the same routing policy.",
        // N-35
        "____ uniquely identifies each Autonomous System in the Internet.",
        // N-36
        "The ASN from Malaysia can be obtained from ____ registry.",
        // N-37
        "One AS has only one connection to another AS. Choose the suitable type for this AS.",
        // N-38
        "BGP uses ____ protocol to establish connections with its peer.",
        // N-39
        "Port number ____ is used by BGP to establish connection with its peer.",
        // N-40
        "The ____ message is used to exchange route between BGP peers.",
        // N-41
        "This type of BGP attribute can be identified by all the BGP routers and must be carried in Update message.",
        // N-42
        "The ____ attribute is used within AS between iBGP peers to determine the best path for the data trafic to exit an AS.",
        // N-43
        "The ____ message is used to establish BGP peer relationship.",
        // N-44
        "____ is a protocol used to exchange routing and network reachability information between AS in the Internet.",
        // N-45
        "172.16.0.1 is a class ____ address.",
        // N-46
        "The class D of an IP address is a ____ address.",
        // N-47
        "Ping and tracert application use ____ protocol to check the reachability of each hop on a forwarding path.",
        // N-48
        "The length of IPv____ address is 32 bits.",
        // N-49
        "____ field in IP header is used to discard a packet and handle routing loop in the Internet.",
        // N-50
        "This is NOT a protocol in network layer.",
        // N-51
        "Which is forwarding data packets between different networks?",
        // N-52
        "What is the purpose of subnetting?",
        // N-53
        "Which is the protocol used in the network layer?",
        // N-54
        "Which protocol is used to assign IP address dynamically?",
        // N-55
        "What is the function of Time-to-live (TTL) in IP header?"
    };

    string[][] answers = new string[][]
    {
        new string[] { "Transport", "Application", "Network" }, // N-1
        new string[] { "5", "4", "6" }, // N-2
        new string[] { "segment", "frame", "packet" }, // N-3
        new string[] { "framing", "encapsulation", "fragmentation" }, // N-4
        new string[] { "TOS", "Flags", "TTL" }, // N-5
        new string[] { "SCTP", "UDP", "ICMP" }, // N-6
        new string[] { "MAC", "URL", "IP" }, // N-7
        new string[] { "255.255.255.255", "255.255.255.0", "255.255.0.0" }, // N-8
        new string[] { "/8", "/32", "/24" }, // N-9
        new string[] { "Network", "Multicast", "Broadcast" }, // N-10
        new string[] { "Multicast", "Anycast", "Network" }, // N-11
        new string[] { "192.168.0.0 - 192.168.255.255", "172.16.0.0 - 172.31.255.255", "10.0.0.0 - 10.255.255.255" }, // N-12
        new string[] { "B", "D", "C" }, // N-13
        new string[] { "Broadcast", "Link-local", "Loopback" }, // N-14
        new string[] { "OSPF", "RIP", "ICMP" }, // N-15
        new string[] { "Switch", "Hub", "Router" }, // N-16
        new string[] { "Mask", "Outbound Interface", "Next Hop" }, // N-17
        new string[] { "Dynamic", "OSPF", "Static" }, // N-18
        new string[] { "Static", "Default", "Direct" }, // N-19
        new string[] { "Default", "Direct", "Dynamic" }, // N-20
        new string[] { "10", "150", "60" }, // N-21
        new string[] { "60", "80", "10" }, // N-22
        new string[] { "Direct", "Static", "Default" }, // N-23
        new string[] { "Link-State", "Exterior Gateway", "Interior Gateway" }, // N-24
        new string[] { "Equal-Cost Route", "Floating Route", "Route Summarization" }, // N-25
        new string[] { "Exterior Gateway", "Distance-Vector", "Link-State" }, // N-26
        new string[] { "60", "10", "0" }, // N-27
        new string[] { "2", "1", "0" }, // N-28
        new string[] { "LSU", "LSA", "Hello" }, // N-29
        new string[] { "HDR", "TDR", "DR" }, // N-30
        new string[] { "Class", "Subnet", "Area" }, // N-31
        new string[] { "ABR", "BR", "ASBR" }, // N-32
        new string[] { "Optional non-transitive", "Well-known discretionary", "Well-known mandatory" }, // N-33
        new string[] { "Authoritative Server", "Authentication System", "Autonomous System" }, // N-34
        new string[] { "CDN", "BSN", "ASN" }, // N-35
        new string[] { "AFRINIC", "ARIN", "APNIC" }, // N-36
        new string[] { "Multihomed", "IXP", "Stub" }, // N-37
        new string[] { "RTP", "SCTP", "TCP" }, // N-38
        new string[] { "180", "125", "179" }, // N-39
        new string[] { "Keepalive", "Open", "Update" }, // N-40
        new string[] { "Optional non-transitive", "Optional transitive", "Well-known Mandatory" }, // N-41
        new string[] { "MED", "AS_Path", "Local Preference" }, // N-42
        new string[] { "Update", "Notification", "Open" }, // N-43
        new string[] { "UDP", "IP", "BGP" }, // N-44
        new string[] { "C", "A", "B" }, // N-45
        new string[] { "Broadcast", "Unicast", "Multicast" }, // N-46
        new string[] { "TCP", "ARP", "ICMP" }, // N-47
        new string[] { "5", "6", "4" }, // N-48
        new string[] { "AS_Path", "Protocol", "TTL" }, // N-49
        new string[] { "ICMP", "IP", "DHCP" }, // N-50
        new string[] { "Cloud", "Switch", "Router" }, // N-51
        new string[] { "Increasing network security", "Improving network performance", "Extending range of IP addresses" }, // N-52
        new string[] { "UDP", "SFTP", "ICMP" }, // N-53
        new string[] { "DNS", "BGP", "DHCP" }, // N-54
        new string[] { "Specifying maximum packet size", "Ensuring error-free data transmission", "Controlling maximum number of hops" } // N-55
    };

    string[] explanations = new string[]
    {
        "Computing protocols like IP (Internet Protocol), OSPF (Open Shortest Path First), and BGP (Border Gateway Protocol) operate at the Network layer, facilitating network communication and routing.", // N-1
        "IPv6 addresses are 128 bits long, representing a significant expansion from the 32-bit length of IPv4 addresses.", // N-2
        "Packets, also known as datagrams, are the fundamental data units used in the Network layer for transmission across networks.", // N-3
        "Fragmentation involves breaking a packet into smaller fragments to fit the Maximum Transmission Unit (MTU) of the network.", // N-4
        "The Time-to-Live (TTL) field in the IP header specifies the number of hops or routers a packet can traverse before being discarded.", // N-5
        "Protocol field value '1' in the IP header identifies the ICMP (Internet Control Message Protocol) used for network management and error reporting.", // N-6
        "IP (Internet Protocol) addresses uniquely identify hosts on a network, enabling data routing and delivery.", // N-7
        "The default subnet mask for Class B IP addresses is '255.255.0.0', allowing for more subnets within the address space.", // N-8
        "The default subnet mask for Class C IP addresses is '/24', indicating a 24-bit subnet mask for network segmentation.", // N-9
        "The Broadcast address is a special IP address used to deliver data packets to all hosts within a network.", // N-10
        "Network addresses are used to identify segments of a network, facilitating routing and data transmission.", // N-11
        "Class A private IP addresses range from '10.0.0.0' to '10.255.255.255', offering a large address space for private networks.", // N-12
        "Class C private IP addresses range from '192.168.0.0' to '192.168.255.255', providing a smaller address space for private networks.", // N-13
        "The '127.0.0.0/8' range is reserved for Loopback addresses, enabling a device to send data to itself for testing and debugging purposes.", // N-14
        "ICMP (Internet Control Message Protocol) serves as an auxiliary protocol to IP, used for error handling and communication between network devices.", // N-15
        "A router is a network device responsible for forwarding packets to their destination subnet based on defined routes.", // N-16
        "The 'Next Hop' component in an IP routing table specifies the next network device address to forward data packets.", // N-17
        "Static routes in a routing table are manually configured by network administrators, offering fixed paths for data transmission.", // N-18
        "Direct routes in a routing table are automatically generated by the router based on its interfaces and connected networks.", // N-19
        "Dynamic routes in a routing table are learned and updated using routing protocols like OSPF, RIP, and BGP.", // N-20
        "The default preference value of a static route in a routing table is '60', indicating its reliability for routing decisions.", // N-21
        "OSPF internal routes have a preference value of '10', highlighting their high preference in routing tables.", // N-22
        "Default routes are used when incoming packets don't match any specific routing entry in an IP routing table.", // N-23
        "OSPF (Open Shortest Path First) and RIP (Routing Information Protocol) are classified as interior gateway protocols operating within an Autonomous System (AS).", // N-24
        "Route summarization helps reduce the size of IP routing tables by aggregating multiple routes into a single summary route.", // N-25
        "OSPF (Open Shortest Path First) is a Link-State routing protocol, considering network topology for routing decisions.", // N-26
        "The preference value of the direct route in a routing table is '0', indicating its high reliability and direct connectivity.", // N-27
        "Area '0' in OSPF (Open Shortest Path First) serves as a backbone area, connecting other OSPF areas.", // N-28
        "Hello packets in OSPF are periodically sent to discover and maintain neighbor relationships between OSPF routers.", // N-29
        "DR (Designated Router) and BDR (Backup Designated Router) are responsible for establishing adjacencies with other OSPF routers.", // N-30
        "An OSPF domain is divided into multiple 'areas' to manage and scale network operation efficiently.", // N-31
        "ASBR (Autonomous System Boundary Router) exchanges routing information between different Autonomous Systems (AS) in BGP.", // N-32
        "The Origin, AS_PATH, and Next-Hop attributes in BGP are considered Well-known Mandatory attributes for routing decisions.", // N-33
        "Autonomous system (AS) is a very large network or group of networks with a single routing policy, which using unique ASN to identify each AS in the global Internet routing system.", // N-34
        "ASNs (Autonomous System Numbers) in Malaysia can be obtained from the APNIC (Asia-Pacific Network Information Centre) registry.", // N-35
        "A 'Stub' AS has only one connection to another AS, limiting the number of connections and paths.", // N-37
        "BGP (Border Gateway Protocol) uses TCP (Transmission Control Protocol) as the underlying protocol for establishing reliable connections with its peers.", // N-38
        "BGP uses port number '179' to establish connections with its peers, allowing communication between BGP routers.", // N-39
        "The 'Update' message is utilized in BGP to exchange routing information and updates between BGP peers.", // N-40
        "Attributes categorized as 'Well-known Mandatory' must be recognized and included by all BGP routers in Update messages.", // N-41
        "The 'Local Preference' attribute in BGP determines the best exit path for data traffic within an AS.", // N-42
        "The 'Open' message initiates the establishment of a BGP peer relationship between routers.", // N-43
        "BGP (Border Gateway Protocol) serves as a protocol for exchanging routing and network reachability information between AS in the Internet.", // N-44
        "IP address '172.16.0.1' falls under Class B addressing, offering private IP space for local networks.", // N-45
        "Class D IP addresses are reserved for multicast group communication, enabling data distribution to multiple recipients.", // N-46
        "ICMP (Internet Control Message Protocol) is utilized by Ping and Tracert applications to verify connectivity and trace network paths.", // N-47
        "IPv4 addresses are 32 bits in length, allowing for a finite number of unique addresses.", // N-48
        "The TTL (Time-to-Live) field in the IP header helps prevent routing loops by discarding packets that exceed their time limit.", // N-49
        "DHCP (Dynamic Host Configuration Protocol) operates in the Application layer, managing IP address assignments in networks.", // N-50
        "Router enable interconnectivity and communication between multiple networks by identifying optimal transmission path based on destination addresses.", // N-51
        "Subnetting extends the range of IP addresses by dividing network into smaller subnet which allows allocation and utilization of IP addresses within each subnet.", // N-52
        "ICMP is used in network layer to provide communication between devices by reporting errors and information. SFTP operates at application layer and UDP operates at transport layer.", // N-53
        "DHCP or Dynamic Host Configuration Protocol dynamically assigns IP addresses to devices on a network to provide efficient and automated network configuration.", // N-54
        "Time-to-Live or TTL in the IP header sets a maximum number of hops a packet can traverse to prevent endless looping and ensure optimal routing in a network." // N-55
    };

    List<int> shuffledIndexes = new List<int>();
    int currentQuestionIndex = 0;

    void Start()
    {
        ShuffleQuestions();
        DisplayNextQuestion();
    }

    void ShuffleQuestions()
    {
        shuffledIndexes.Clear();
        for (int i = 0; i < questions.Length; i++)
        {
            shuffledIndexes.Add(i);
        }
        for (int i = 0; i < shuffledIndexes.Count; i++)
        {
            int temp = shuffledIndexes[i];
            int randomIndex = Random.Range(i, shuffledIndexes.Count);
            shuffledIndexes[i] = shuffledIndexes[randomIndex];
            shuffledIndexes[randomIndex] = temp;
        }
    }

    void DisplayNextQuestion()
    {
        if (currentQuestionIndex >= shuffledIndexes.Count)
        {
            currentQuestionIndex = 0;
            ShuffleQuestions();
        }

        if (shuffledIndexes.Count == 0)
        {
            Debug.LogError("No questions available.");
            return;
        }

        int index = shuffledIndexes[currentQuestionIndex];

        questionText.text = questions[index];

        string[] selectedAnswers = answers[index];
        string explanation = explanations[index];

        if (selectedAnswers.Length >= 3)
        {
            answer1Text.text = selectedAnswers[0];
            answer2Text.text = selectedAnswers[1];
            answer3Text.text = selectedAnswers[2];
        }
        else
        {
            Debug.LogError("Not enough answer: " + questions[index]);
        }

        explanationText.text = explanation;
        currentQuestionIndex++;
    }
}